name = "telier-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "telier-db"
database_id = "4ea87f58-e284-4fef-847c-93de662b43f4"

[vars]
ALLOWED_ORIGIN = "https://telier.pages.dev"
AUTO_SCHEMA_SYNC = "0"
